// Generated by gencpp from file myservice/add.msg
// DO NOT EDIT!


#ifndef MYSERVICE_MESSAGE_ADD_H
#define MYSERVICE_MESSAGE_ADD_H

#include <ros/service_traits.h>


#include <myservice/addRequest.h>
#include <myservice/addResponse.h>


namespace myservice
{

struct add
{

typedef addRequest Request;
typedef addResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct add
} // namespace myservice


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::myservice::add > {
  static const char* value()
  {
    return "4781436a0c2affec8025955a6041e481";
  }

  static const char* value(const ::myservice::add&) { return value(); }
};

template<>
struct DataType< ::myservice::add > {
  static const char* value()
  {
    return "myservice/add";
  }

  static const char* value(const ::myservice::add&) { return value(); }
};


// service_traits::MD5Sum< ::myservice::addRequest> should match
// service_traits::MD5Sum< ::myservice::add >
template<>
struct MD5Sum< ::myservice::addRequest>
{
  static const char* value()
  {
    return MD5Sum< ::myservice::add >::value();
  }
  static const char* value(const ::myservice::addRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::myservice::addRequest> should match
// service_traits::DataType< ::myservice::add >
template<>
struct DataType< ::myservice::addRequest>
{
  static const char* value()
  {
    return DataType< ::myservice::add >::value();
  }
  static const char* value(const ::myservice::addRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::myservice::addResponse> should match
// service_traits::MD5Sum< ::myservice::add >
template<>
struct MD5Sum< ::myservice::addResponse>
{
  static const char* value()
  {
    return MD5Sum< ::myservice::add >::value();
  }
  static const char* value(const ::myservice::addResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::myservice::addResponse> should match
// service_traits::DataType< ::myservice::add >
template<>
struct DataType< ::myservice::addResponse>
{
  static const char* value()
  {
    return DataType< ::myservice::add >::value();
  }
  static const char* value(const ::myservice::addResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MYSERVICE_MESSAGE_ADD_H
